# 11. 연습문제

In [1]:
import numpy as np

In [3]:
vec = np.zeros(10)
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.eye(1, 10, k = 5)

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [15]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [42]:
np.arange(10, 50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [17]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
a = np.array([1, 2, 0, 0, 4, 0])
a[a != 0]

array([1, 2, 4])

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
b = np.random.randint(0, 9, 9).reshape(3, 3)
b

array([[4, 8, 3],
       [1, 5, 3],
       [3, 3, 0]])

In [34]:
print(np.max(b))
print(np.min(b))

8
1


In [35]:
np.mean(b, axis = 0) # 열 평균

array([4.        , 5.66666667, 6.66666667])

In [36]:
np.mean(b, axis = 1) # 행 평균

array([6.        , 5.33333333, 5.        ])